### PR TITLE
WIP: Support Babel 7

### PR DESCRIPTION
**Pull request by jamesreggio**
`@babel/template` has a new API in Babel 7 that requires positional replacements (i.e., those with numbered placeholders like `$0` and `$1`) to be passed in via a single array argument.

This PR makes the needed change, which was all that was needed to get this plugin to run in a Babel 7 environment.

The PR is not clean to merge because it regresses Babel 6 functionality. I would suggest updating the package dependencies to Babel 7 if you'd like to eventually merge this — though the `lazy` option in the Babel 7 commonjs plugin may obviate the need for this package, per the [discussion here](https://github.com/babel/babel/pull/6952#issuecomment-348734019).

### CODE REVIEW

**Comment by milesj** [comment]
@zertosh This is needed to unblock Babel 7 for Jest: https://github.com/facebook/jest/pull/6949

**Comment by zertosh** [comment]
@milesj, the tests are failing

**Comment by milesj** [comment]
@jamesreggio Ping

**Comment by jamesreggio** [comment]
Sorry, @zertosh and @milesj, but all of the tests need to be migrated to Babel 7. I spent an hour on it so far and cannot even get a single test to run on Babel 7. I don't have any more time to spend, especially since I'm not using this package myself. (We're just using the `lazy` option from the first-party `@babel/plugin-transform-modules-commonjs` itself, per [these docs](https://babeljs.io/docs/en/next/babel-plugin-transform-modules-commonjs.html#lazy).)

I'm going to close this, but you may consider using my adjustments to the plugin code in any future attempt you make to support Babel 7.

**Pull request closed without merging**
